image: pkubanek/rts2

stages:
  -build
  -test

build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure
    - make

test:
  stage: test
  script:
    - ./autogen.sh
    - ./configure
    - make check
